version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install aws-sam-cli
      - cd jfcm-sam
      - pip install -r tests/unit/requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo "Running sam build..."
      - sam build

  build:
    commands:  
      - echo "Running sam package..."
      - sam package --output-template-file packaged.yaml --s3-bucket evento-4-jfcm

  post_build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/unit

artifacts:
  files:
    - jfcm-sam/packaged.yaml
