version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install aws-sam-cli
      - pip install pytest
      - cd jfcm-sam

  pre_build:
    commands:
      - echo "Running sam build..."
      - sam build

  build:
    commands:  
      - echo "Running sam package..."
      - sam package --output-template-file packaged.yaml --s3-bucket evento-4-jfcm
      - pytest tests/unit

artifacts:
  files:
    - jfcm-sam/packaged.yaml
